
type BubbleChartOda {
  uid: String
  id: String
  year: Int
  name: String
  income_group: String
  region: String
  revenuePerPerson: Float
  numberInExtremePoverty: Float
  indicatorValue: Float
}

type BubbleChartPoverty {
  uid: String
  id: String
  year: Int
  name: String
  income_group: String
  region: String
  revenuePerPerson: Float
  percentageInExtremePoverty: Float
  indicatorValue: Float
}

type Query {
  bubbleChartOda(indicatorId: String!): BubbleChartOda
  bubbleChartPoverty(indicatorId: String!): BubbleChartPoverty
  
  # IdNamePair is defined in unbundling aid types 
  # this list feeds off oda table from countries and global/concept file
  bubbleChartIndicatorsList: [IdNamePair]
}

